#!/bin/bash

capacity=$(cat /sys/class/power_supply/BAT0/capacity)
status=$(cat /sys/class/power_supply/BAT0/status)

if [ "$status" = "Charging" ]; then
    if [ "$capacity" -ge 100 ]; then
        icon="󰂅 "
    elif [ "$capacity" -ge 90 ]; then
        icon="󰂋 "
    elif [ "$capacity" -ge 80 ]; then
        icon="󰂊 "
    elif [ "$capacity" -ge 70 ]; then
        icon="󰢞 "
    elif [ "$capacity" -ge 60 ]; then
        icon="󰂉 "
    elif [ "$capacity" -ge 50 ]; then
        icon="󰢝 "
    elif [ "$capacity" -ge 40 ]; then
        icon="󰂈 "
    elif [ "$capacity" -ge 30 ]; then
        icon="󰂇 "
    elif [ "$capacity" -ge 20 ]; then
        icon="󰂆 "
    else
        icon="󰢜 "
    fi
else
    if [ "$capacity" -ge 100 ]; then
        icon="󰁹 "
    elif [ "$capacity" -ge 90 ]; then
        icon="󰂂 "
    elif [ "$capacity" -ge 80 ]; then
        icon="󰂁 "
    elif [ "$capacity" -ge 70 ]; then
        icon="󰂀 "
    elif [ "$capacity" -ge 60 ]; then
        icon="󰁿 "
    elif [ "$capacity" -ge 50 ]; then
        icon="󰁾 "
    elif [ "$capacity" -ge 40 ]; then
        icon="󰁽 "
    elif [ "$capacity" -ge 30 ]; then
        icon="󰁼 "
    elif [ "$capacity" -ge 20 ]; then
        icon="󰁻 "
    else
        icon="󰁺 "
    fi
fi

echo "$icon$capacity%"
