#!/bin/bash
player_name=$(playerctl metadata --format '{{playerName}}')
player_status=$(playerctl status)

if [[ "$player_status" == "Playing" ]]; then
  song_info+=$(playerctl metadata --format '{{artist}}: {{title}}')
else
  song_info=' 󰎊 Not Playing '
fi

echo "$song_info" 
